<?php

namespace App\Models;

use App\Observers\ModelObserve;
use Illuminate\Database\Eloquent\Model;
use Auth;

class BaseModel extends Model
{

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(ModelObserve::class);
    }

    public function scopeUserID($query){

        return $query->where('user_id',Auth::guard('api')->user()->id);
    }


}
